### ISSUE TITLE
Install behind corporate firwall

### ISSUE THREAD

**Issue by vahiri** [angular-redux/platform#73]
Hi,

We are using angular 7 in our company.

Our company has corporate firewall that is blocking github standard repository for npm install and instead using a private repository. Your library does not exist in that repository and I am not able to download from github repository. I also tried to download the source and package it myself but had so many errors circular dependencies etc. Any chance someone can prepackage latest version of all 3 packages (store, form and router), that way I will just upload them to private repository and it will be available for everyone including myself.

Thanks,
V

**Comment by smithad15** [comment]
If your company is using an internal NPM mirror like Artifactory or Nexus, you will need to talk to whomever is managing that tool so that they add the release binaries from the public npm repository for you to use. I would highly suggest against manually including dependencies outside of a package manager.
