### ISSUE TITLE
Upgrade Angular + CLI for example app

### ISSUE THREAD

**Issue by smithad15** [angular-redux/platform#8]
The current example app is still running Angular 4 and associated dependencies. This need to be brought up to date.

**Comment by milocosmopolitan** [comment]
Hi @smithad15, first thank you for the great product. I've been consuming `@angular-redux/store`, `@angular-redux/router`, `@angular-redux/form` more than a year on various angular 4+ projects, and it has been helping me a lot. Recently projects that I've been working on faced issues utilizing your `@angular-redux/store` with route lazy-load. Although `@ngrx` does resolve this, I still want to stay with your product and was hoping to get involved contributing to library which I am heavily depend on. At this moment, my project need a small POC with your packages with route lazyload, and I think this might be perfect time for me to help you update example app with lazyload implementation. If you can share your vision and knowledge how I should approach this, I would be more than happy to make contribution. Let me know ;)

**Comment by smithad15** [comment]
Hey @milocosmopolitan. Thanks for your support of the library and volunteering to help. Supporting lazy loading is definitely on the feature roadmap for v10. Right now, we are going through a phase of technical debt reduction and making it easier for folks like yourself to be able to contribute. At the moment, it would be a bit difficult for you to get onboard unfortunately. I'm hoping to get that resolved soon so that we can ensure the quality and stability of the library going forward. Because of that, we won't be adding new features for awhile as we clean house. Please do keep an eye on the repo and my apologies that I don't have a better answer regarding lazy loading support at this moment.

**Comment by milocosmopolitan** [comment]
Hi @smithad15 makes sense. I was able to resolve route lazyloading issue without making any changes to your actually library. On our project we used to consume the code on example app with `StoreModule` initializing redux store on its constructor, but instead of going with that approach we created `StoreService` which wraps `NgRedux` service and has its own method to initialize redux store using injection tokens of reducers, epics, and etc..  This service is now provided on `app.module.ts` as application wide dependency injection and runs store init method on constructor of `AppModule`, then I was able to support route lazyload. Therefore I think the solution for lazyloading is really nothing to do with the actual source code of your library but perhaps have other examples to achieve that would help consumers big time. When I get a chance I will create small example repo and share.

**Comment by smithad15** [comment]
Glad you were able to figure out a solution around it for now. Would love to see an example repo if you get a chance. While the openness of this library does allow workarounds like you described, I do still have a goal of providing a simpler API for the library so that you don't have to worry as much about the registration details

**Comment by szb512** [comment]
#77 refers to this as well.
